import { Box, Flex, Separator, Text, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoginButton } from "./components/LoginButton";
import { SignupButton } from "./components/SignupButton";
import { LogoutButton } from "./components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <Box>
            <Flex align="baseline" justify="between" px="6" pt="4" pb="2">
              <Text className="text-2xl font-bold">Logo</Text>
              <Flex gap="4">
                <LoginButton />
                <LogoutButton />
                <SignupButton />
              </Flex>
            </Flex>
            <Separator my="3" size="4" />
          </Box>
          <Box>{children}</Box>
        </Theme>
      </body>
    </html>
  );
}
